apiVersion: v1
kind: Service
metadata:
  labels:
    app: data-couchbase
    env: dev
  name: svc-data-couchbase
  annotations:
    metrics.dynatrace.com/port: '9420'
    metrics.dynatrace.com/scrape: 'true'
    metrics.dynatrace.com/secure: 'true'
    metrics.dynatrace.com/path: '/metrics'
spec:
  ports:
  - name: tcp-web-cb
    port: 8091
    protocol: TCP
    targetPort: 8091
  - name: tcp-memcached-cb
    port: 11210
    protocol: TCP
    targetPort: 11210
  - name: dynatrace-monitoring-node-exporter-port
    port: 9420
  selector:
    app: data-couchbase
    env: dev
  type: LoadBalancer
  externalIPs:
  - 172.16.100.2
